packages:
  - 'packages/*'
overrides:
  node-loggly-bulk: ^4.0.2
  axios: ^1.15.0
  fast-xml-parser: ^5.7.0
onlyBuiltDependencies:
  - dtrace-provider
  - esbuild
  - nx
  - sqlite3
minimumReleaseAge: 1440
catalog:
  sinon: 22.0.0
  typescript: 5.9.3
