name: Test
on:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ 22, 24 ]
    env:
      FORCE_COLOR: 1
    name: Node ${{ matrix.node }}
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
        with:
          fetch-depth: 0
      - uses: pnpm/action-setup@0ebf47130e4866e96fce0953f49152a61190b271 # v6
      - uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6
        env:
          FORCE_COLOR: 0
        with:
          node-version: ${{ matrix.node }}
          cache: pnpm

      - uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6
        with:
          path: .nx/cache
          key: nx-${{ runner.os }}-node${{ matrix.node }}-${{ hashFiles('pnpm-lock.yaml') }}-${{ github.sha }}
          restore-keys: |
            nx-${{ runner.os }}-node${{ matrix.node }}-${{ hashFiles('pnpm-lock.yaml') }}-
            nx-${{ runner.os }}-node${{ matrix.node }}-

      - uses: nrwl/nx-set-shas@afb73a62d26e41464e9254689e1fd6122ee683c1 # v5
        if: github.event_name == 'pull_request'

      - run: pnpm install --prefer-offline --frozen-lockfile
      - run: pnpm format:check
      - run: pnpm lint

      - name: Test affected (PRs)
        if: github.event_name == 'pull_request'
        run: pnpm exec nx affected -t test --output-style=static

      - name: Test all (main)
        if: github.event_name == 'push'
        run: pnpm test:ci

      - uses: codecov/codecov-action@fb8b3582c8e4def4969c97caa2f19720cb33a72f # v7

      - uses: tryghost/actions/actions/slack-build@4d127f5388618fd9dc260e8ef4a64777f8b564cb # main
        if: failure() && github.event_name == 'push' && github.ref == 'refs/heads/main'
        with:
          status: ${{ job.status }}
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

  test-results:
    runs-on: ubuntu-latest
    name: All tests pass
    permissions: {}
    needs: [test]
    if: always()
    steps:
      - run: |
          result="${{ needs.test.result }}"
          if [[ $result == "success" || $result == "skipped" ]]; then
            exit 0
          else
            exit 1
          fi
