name: Test
on:
  pull_request:
  push:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ 22, 24 ]
    env:
      FORCE_COLOR: 1
    name: Node ${{ matrix.node }}
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          fetch-depth: 0
      - uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6
        env:
          FORCE_COLOR: 0
        with:
          node-version: ${{ matrix.node }}
          cache: yarn

      - run: yarn --prefer-offline --frozen-lockfile
      - run: yarn test:ci

      - uses: codecov/codecov-action@75cd11691c0faa626561e295848008c8a7dddffe # v5

      - uses: tryghost/actions/actions/slack-build@ae42d6e652b420692853b65cefd06a0443ea3885 # main
        if: failure() && github.event_name == 'push' && github.ref == 'refs/heads/main'
        with:
          status: ${{ job.status }}
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

  test-results:
    runs-on: ubuntu-latest
    name: All tests passed
    needs: [test]
    if: always()
    steps:
      - run: |
          result="${{ needs.test.result }}"
          if [[ $result == "success" || $result == "skipped" ]]; then
            exit 0
          else
            exit 1
          fi
